### ISSUE TITLE
Weird Date implementation on iOS causes the count down to break because of weird date string

### ISSUE THREAD

**Issue by camtheman256** [camtheman256/LASA-Schedules#11]
iOS includes a time zone with our date string so we may want to consider compiling date strings ourselves using gethours, getminutes, and so on.
Method for myApp maybe?

**Comment by alexdloia** [comment]
Or splice the string before the timezone? Shouldn't be a problem on other platforms.

**Comment by alexdloia** [comment]
Or we can use `.toTimeString` instead which returns in the format *HH:MM:SS GMT-TTTT* and splice out the timezone part at the end.

**Comment by camtheman256** [comment]
Maybe. I've determined this is an iOS 9 problem, doesn't occur on later iOS for some reason. Whatever you feel like is good.

**Comment by alexdloia** [comment]
If deployment to iOS is ever seriously considered, we can address this issue.

**Comment by camtheman256** [comment]
Yeah. Again, iOS 9 is all we have to worry about and like, [**this**](https://developer.apple.com/support/app-store/) is how iOS works so I'm not all that concerned:

**Comment by camtheman256** [comment]
Don't really want to care or care to fix this.
