### ISSUE TITLE
Updates for 2018-2019

### ISSUE THREAD

**Issue by griffindvs** [camtheman256/LASA-Schedules#20]
The app needs the following updates for the 2018-2019 school year:
- New schedules all around ([see my fork](https://github.com/griffindvs/LASA-Schedules))
- Special schedule days for late starts, c-days, PSAT, pep rallies
- Implementation of Wednesdays with FIT
- Movement to schedules.lasa2019.com in the config to replace floating.website
- C-Day schedule from the new agenda
- Readme update that gives information on the app, schedule updating, etc.

**Comment by camtheman256** [comment]
All schedules on the website are now stored in a JSON file with dates, Wednesdays with FIT are implemented, C-day schedule is not updated yet, please add a separate issue for that, README will be updated soon.
